# syntax = edrevo/dockerfile-plus

FROM --platform=linux/amd64 mcr.microsoft.com/vscode/devcontainers/base:0-bullseye

USER vscode
ENV HOME=/home/vscode

RUN sudo apt install lsb-release

INCLUDE+ Dockerfile.base
