# syntax = edrevo/dockerfile-plus

FROM gitpod/workspace-full

USER gitpod
ENV HOME=/home/gitpod

INCLUDE+ Dockerfile.base

RUN ${DENO_INSTALL}/bin/deno completions bash > /home/gitpod/.bashrc.d/90-deno
