# syntax = edrevo/dockerfile-plus

FROM --platform=linux/amd64 mcr.microsoft.com/vscode/devcontainers/base:0-bullseye

USER vscode
ENV HOME=/home/vscode

RUN sudo DEBIAN_FRONTEND=noninteractive apt-get -y update
RUN sudo DEBIAN_FRONTEND=noninteractive apt -y install software-properties-common

INCLUDE+ Dockerfile.base
