# install deno
ENV DENO_INSTALL=~/.deno
RUN mkdir -p /deno \
    && curl -fsSL https://deno.land/x/install/install.sh | sh

ENV PATH=${DENO_INSTALL}/bin:${PATH} \
    DENO_DIR=${DENO_INSTALL}/.cache/deno

# install llvm
RUN wget https://apt.llvm.org/llvm.sh
RUN sudo chmod +x llvm.sh && sudo ./llvm.sh 14
